config/routes.rb
SeatYourself::Application.routes.draw do
  
  resources :restaurants do
    resources :reservations, :only => [:create]
  end

  resources :users, :except => [:index]
  resources :sessions, :only => [:new, :create, :destroy]

  root 'restaurants#index'

  get 'signup', to: 'users#new', as: 'signup' 
  get 'login', to: 'sessions#new', as: 'login'
end

  

app/models/genre.rb
class Genre < ActiveRecord::Base
  
has_many :genres_restaurants
has_many :restaurants, :through => :genres_restaurants


  def self.cuisine
      @cuisine
  end
end

app/models/genres_restaurant.rb
class GenresRestaurant < ActiveRecord::Base
  
  belongs_to :restaurant
  belongs_to :genre  

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

  belongs_to :restaurant
  belongs_to :user

  def index
    @reservations=Reservation.all
  end

  def show
    @reservation=Reservation.find(params[:id])
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  # has_many :genres_restaurants
  # has_many :genres, :through => :genres_restaurants
  has_many :reservations
  mount_uploader :restaurant_picture
  validates :postal_code, :price_range, presence: true

  # def self.price_ranges
  #   %w(Low Medium High)
  # end

  def time_slots
    collection=[]
    start_time=Time.now.beginning_of_hour
    end_time=Time.now.tomorrow.midnight-1.hour
    time=start_time

    while time < end_time
      collection<<[time.beginning_of_hour.hour, time.beginning_of_hour]
      time=time+1.hour
    end

    collection
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
<<<<<<< HEAD

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :full_name, presence: true
=======
  validates :email, presence: true
  has_many :reservations
>>>>>>> 74039c72f6a19f7261bc706af67ea3f42a2ac45f
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # def ensure_logged_in
  #   unless current_user
  #   redirect_to new_session_path
  #   end
  # end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

 def create

  @restaurant=Restaurant.find(params[:restaurant_id])
  @reservation = Reservation.create(reservation_params)
  @reservation.user_id=current_user.id
  @reservation.restaurant_id=@restaurant.id
  if @reservation.save
    redirect_to current_user
  else
    render "/restaurants/show", :id=>@restaurant.id
  end

 end
 
 private

 def reservation_params
   params.require(:reservation).permit(:notes, :user_id, :reserved_time, :reserved_day, :party_size) 
 end 
end

app/controllers/reservations_controller_controller.rb
class ReservationsControllerController < ApplicationController
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all 
    @genres = Genre.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reservation = Reservation.new(:restaurant_id=>@restaurant.id)
    respond_to do |format|
      format.html
      format.js {}
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
   
    if @restaurant.save
      redirect_to @restaurant
    else
      render "new"
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    #params = {genre_ids = ["", "2"]}
    # params[:genre_ids].each do |genre_id|
    #   restaurant.genres << genre_id unless genre_id.blank?
    # end
    if 
      @restaurant.update(restaurant_params)
        render partial: "address"
        # redirect_to @restaurant
    else
      render json:{errors:@restaurant.errors.full_messages}
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
  end
  
private 

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :postal_code, :genre_ids, :price_range, :restaurant_picture)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user=User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_path, :notice => "You have been logged in with email #{user.email}"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_path, :notice => "You have been logged out."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end

  def new
    @user = User.new
  end

<<<<<<< HEAD
	def create
  	@user = User.create(user_params)

  	if @user.save
  		redirect_to @user
  	else
  		render "new"
  	end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

  private 
=======
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

>>>>>>> 74039c72f6a19f7261bc706af67ea3f42a2ac45f
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :full_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_controller_helper.rb
module ReservationsControllerHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/_navigation.html.erb
<div class="navbar row nav1">
      <a class="toggle" gumby-trigger="#example-nav &gt; .nav1 &gt; ul" href="#"><i class="icon-menu" title=".icon-menu"></i></a>
      <h1 class="four columns logo">
        <%= link_to image_tag("my_restaurant.png", :class => "logo_height"), root_path %>
        </a>
      </h1>
      <ul class="eight columns">
        <li id="create_restaurant">
        	<%= link_to("Create a Restaurant ", new_restaurant_path) %>
        </li>
        <li>
        <li>
          <%= link_to("Sign Up ", new_user_path) %>
        </li>
          <% if current_user.nil? %>
          <%= link_to("Log In", "/login", :id => "loginbutton" , :remote=>true) %>
          <% else %>
          <li style="color:yellow;"><%= link_to(current_user.email, current_user) %></li>
          <%= link_to("Log Out", session_path("current"), :method => :delete ) %>
          <% end %>
      </ul>
      <%= render "sessions/form" %>
    </div>

<script>

$("#loginbutton").click(function(e) {
  e.preventDefault();
  $( "#login-bar" ).toggle( "fade", 1000 );
});

// $('#create_restaurant').on('click', function(e) {
//   e.preventDefault();
// });


</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeatYourself</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag :modernizr %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
   <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="row">
	  <div class="twelve columns">
	  	<%= render 'layouts/navigation' %>
	    <%= yield %>
	  </div>
	</div>
<!-- 	<%= debug(params) %>
 --></body>
</html>

app/views/restaurants/_address.html.erb
  <div id="restaurant_info">
    
    <%= @restaurant.address %>
    <br/>
    <%= @restaurant.city %>
    <br/>
    <%= @restaurant.postal_code %>
    <br/>
    Price Range: <%= @restaurant.price_range %>
    <br/>
  
  </div>

app/views/restaurants/_form.html.erb
  
  
  <div class="row">
    <div class="ten columns">
      <div class="field">  
          <ul>       
            <%= form_for(@restaurant, :class=>"rest-update-form", :remote=>true) do |f| %>
                <div class="errors"></div>
      
                <%= f.label :name, for: "res-name", class: "inline" %>
                <%= f.text_field :name, id: "res-name", placeholder: "restaurant name", class: "input" %>
<<<<<<< HEAD
              </li>
              

              <li class="field">
                <%= f.label :address, for: "res-address", class: "inline"  %>
                <%= f.text_field :address,  id: "res-address", placeholder: "restaurant address", class: "input" %>
              </li>

              <li class="field">
                <%= f.label :city, for: "res-city", class: "inline"  %>
                <%= f.text_field :city,  id: "res-city", placeholder: "restaurant city ", class: "input" %>
              </li>

              <li class="field">
                <%= f.label :postal_code, for: "res-postal_code", class: "inline" %>
                <%= f.text_field :postal_code,  id: "res-postal_code", placeholder: "postal code", class: "input" %>
              </li>

              <li class="field">
                <%= f.label :cuisine, class: "inline" %>
                <div class="picker">
                 <%= f.collection_select(:genre_ids, Genre.all, :id, :cuisine, :prompt => true) %>
               </div>
              </li>

              <li class="field">
                <label class="inline"><%= f.label :price_range %></label>
                <div class="picker">
                    <%= f.select :price_range, Restaurant.price_ranges, :prompt => true %>
=======
                <br><br>
                <%= f.label :address, for: "res-name", class: "inline"  %>
                <%= f.text_field :address,  id: "res-name", placeholder: "restaurant address", class: "input" %>
                <br><br>
                <%= f.label :city, for: "res-name", class: "inline"  %>
                <%= f.text_field :city,  id: "res-name", placeholder: "restaurant city ", class: "input" %>
                <br><br>
                <%= f.label :postal_code, for: "res-name", class: "inline" %>
                <%= f.text_field :postal_code, id: "res-name", placeholder: "postal code", class: "input" %>
                <br><br>
                <%= f.label "Upload an Image" %>
                <%= f.file_field :restaurant_picture %>
                <br><br>
                <div class="five columns">
                <%= f.label :price_range %>
                <%= f.select :price_range, options_for_select(["$", "$$", "$$$", "$$$$", "$$$$$",]) %>
>>>>>>> 74039c72f6a19f7261bc706af67ea3f42a2ac45f
                </div>
                
                <br>
                <div class="ten columns">
                <%= f.submit class: "medium metro rounded btn default", type: "submit"  %>
            <% end %>
          </ul>
    </div>
  </div>
</div>

app/views/restaurants/edit.html.erb
<h1> Edit Restaurant </h1>
<%= render 'form' %>

app/views/restaurants/edit.js.erb
alert("hi there! You have an error")

app/views/restaurants/index.html.erb
<h2> All Restaurants </h2>

<% @restaurants.each do |restaurant| %>
	
		<div class="restaurant_wrapper">

	    <div class="seven columns">	
	      <h3><%= link_to(restaurant.name, restaurant)  %></h3>
	<!--       <p><%= restaurant.address %></p>
	      <p> <%= restaurant.city %></p>
	      <p><%= restaurant.postal_code %></p> -->
	    </div>
	 
		</div>

		<%= link_to " Edit ", edit_restaurant_path(:id), class: "medium metro rounded btn default" %>
		
		<%= link_to " Delete ", @restaurant, :confirm => "Are you sure you want to delete this restaurant?",:method => :delete %>

	
	<% end %>
	<div class="bottombar" style="min-width:100%; background-color:grey; position: absolute; top:100%">
	<button><%= link_to(" Create a Restaurant ", new_restaurant_path )%></button>
	</div>

app/views/restaurants/new.html.erb
<h2>Create Restaurant</h2>
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1 class="rest_name"><%= @restaurant.name %></h1>

<div id="modal_edit_form" style="display:none">
<%= render "form" %>
</div>

<div class="five columns">

  <%= render "address" %>  

</div>

<div class="six columns">
  <%= image_tag @restaurant.restaurant_picture if @restaurant.restaurant_picture? %>
</div>
</div>

<% if current_user.nil? %>
  <%= link_to("You must login to create a reservation", new_session_path) %>
<% else %>
  <%= render "/shared/errors", :object_type=>@reservation %>
  <div class="reservation_form">
  <%= form_for [@restaurant, @reservation] do |f| %>
  <%= f.label "Party Size" %>
  <%= f.select("party_size", (1..10).map {|i| [ "#{i} people", i ] }) %>
  <%= f.label "Reservation Day" %>
  <%= f.text_field :reserved_day %>
  <%= f.label "Reservation Time" %>
  <%= f.select("reserved_time", @restaurant.time_slots) %>
  <%= f.label "Notes" %>
  <%= f.text_area :notes %>
  <%= f.submit %>
  <% end %>
  </div>
<% end %>



<button><%= link_to("Back to Home Page", restaurants_path) %></button>
<button id="editbutton"><%= link_to("Edit Restaurant", edit_restaurant_path(@restaurant) )  %></button>
<script>

$('#reservation_reserved_day').datepicker({
  dateFormat: 'MM dd'
});

$('#editbutton').on('click', function(e) {
  e.preventDefault();
  $("#modal_edit_form").dialog({
      autoOpen: true,
      height: 600,
      width: 600,
      modal: true,
      title: 'Edit Restaurant'
  });
});



</script>

app/views/restaurants/show.js.erb
$("#modal_edit_form").dialog( "close" );
$("#restaurant_info").html("<%= j render 'address' %>")

app/views/shared/_errors.html.erb
<% unless object_type.errors.empty? %>

<div id ="errorblock">
  <%= pluralize(object_type.errors.count, "error") %> prevented this from being saved 
  <ul>
    <% object_type.errors.full_messages.each do |error| %>
      <li class="errormessage"> <%= error %> </li>
    <% end %>
  </ul>
</div>

<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      </ul>
    </div>
  <% end %>
<<<<<<< HEAD
=======
  <% end %>
  
  <%= f.label :full_name, 'Full Name:', for: "res-name", class: "inline" %>
  <%= f.text_field :full_name, id: "res-name", placeholder: "full name", class: "input" %>
  <br/>
  
    <%= f.label :email, 'Email:', class: "inline" %>
    <%= f.text_field :email, placeholder: "email address", class: "input" %>
  <br/>
  
    <%= f.label :password, 'Password:', class: "inline" %>
    <%= f.text_field :password, placeholder: "password", class: "input" %>
  <br/>
  
    <%= f.label :password_confirmation, 'Confirm Password:', class: "inline" %>
    <%= f.text_field :password_confirmation, placeholder: "password", class: "input"  %>
  <br/>
  
  <%= f.submit 'Sign Up' %>
>>>>>>> 74039c72f6a19f7261bc706af67ea3f42a2ac45f
<% end %>

  <li class="field">
    <%= f.label :full_name, 'Full Name:', for: "res-full_name", class: "inline" %>
    <%= f.text_field :full_name, id: "res-full_name", placeholder: "full name", class: "input" %>
  </li>

  <li class="field">
    <%= f.label :email, 'Email:', class: "inline", for: "res-email"  %>
    <%= f.text_field :email,  id: "email", placeholder: "restaurant address", class: "input" %>
  </li>

  <li class="field prepend">
    <%= f.label :password, 'Password:', class: "inline", for: "res-name"  %>
    <br>
    <span class="adjoined">@</span>
    <%= f.text_field :password, type: "password", id: "password", placeholder: "restaurant address", class: "input" %>
  </li>
  
  <li class="field prepend">
    <%= f.label :password_confirmation, 'Confirm Password:', class: "inline"  %>
    <br>
    <span class="adjoined">@</span>
    <%= f.text_field :password_confirmation, type: "password", placeholder: "restaurant address", class: "input" %>
  </li>
  
  <li class="field">
  <%= f.submit 'Sign Up', class: "medium metro rounded btn default", type: "submit" %>
  </li>

<% end %>

app/views/users/index.html.erb
<h1>Index View for Users</h1>

Eventually admin only view

<ul>
<% @users.each do |user| %>
<li><%= link_to(user.email,user) %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<div class="row">
	<div class="eight columns">
		<div class="field">  
			<ul>  
			<%= render partial: 'form' %>
			</ul>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<<<<<<< HEAD
<h2>Account Information</h2>

<p> Your name: <strong><%= @user.full_name %></strong></p>
<p>Your email: <strong><%= @user.email %></strong></p>
  
=======
<h1>User Profile</h1>

<%= @user.email %>

<h2>Your Reservations</h2>
<% unless @user.reservations.nil?  %>
  <% @user.reservations.each do |reservation| %>
      <div class = "reservation_block" style="padding:10px">
      <%= link_to(reservation.restaurant.name, reservation.restaurant) %>
      <br>Party Size: <%= reservation.party_size %>
      <br>Day: <%= "#{Time.now.month} #{reservation.reserved_day}" %>
      <br>Time: <%= reservation.reserved_time.hour %>
      <% unless reservation.notes.empty? %><br>Notes:<br><%= reservation.notes %><% end %>
      </div>
  <% end %>
<% end %>
>>>>>>> 74039c72f6a19f7261bc706af67ea3f42a2ac45f